<a href="https://colab.research.google.com/github/siddhipawar645/Python_Optional25/blob/main/Optional25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.ensemble import (
    RandomForestRegressor,
    AdaBoostRegressor,
    GradientBoostingRegressor
)
from xgboost import XGBRegressor
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

In [36]:
df = pd.read_csv("Gold_Dataset.csv")

In [37]:
df.head()

,Date,SPX,GLD,USO,SLV,EUR/USD,Price,Volume,Market_Cap
0,01-02-2008,1447.160034,84.860001,78.470001,15.180,1.471692,84.860001,9076,770189.37
1,01-03-2008,1447.160034,85.570000,78.370003,15.285,1.474491,85.570000,5901,504948.57
2,01-04-2008,1411.630005,85.129997,77.309998,15.167,1.475492,85.129997,6923,589354.97
3,01-07-2008,1416.180054,84.769997,75.500000,15.053,1.468299,84.769997,8517,721986.06
4,01-08-2008,1390.189941,86.779999,76.059998,15.590,1.557099,86.779999,4842,420188.76

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2290 entries, 0 to 2289
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        2290 non-null   object
 1   SPX         2290 non-null   float64
 2   GLD         2290 non-null   float64
 3   USO         2290 non-null   float64
 4   SLV         2290 non-null   float64
 5   EUR/USD     2290 non-null   float64
 6   Price       2290 non-null   float64
 7   Volume      2290 non-null   int64
 8   Market_Cap  2290 non-null   float64
dtypes: float64(7), int64(1), object(1)
memory usage: 161.1+ KB

In [39]:
df.isnull().sum()

Date          0
SPX           0
GLD           0
USO           0
SLV           0
EUR/USD       0
Price         0
Volume        0
Market_Cap    0
dtype: int64

In [40]:
df.fillna(df.mean(numeric_only=True), inplace=True)

df.isnull().sum()

Date          0
SPX           0
GLD           0
USO           0
SLV           0
EUR/USD       0
Price         0
Volume        0
Market_Cap    0
dtype: int64

In [41]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

df.head()

,Date,SPX,GLD,USO,SLV,EUR/USD,Price,Volume,Market_Cap
0,0,1447.160034,84.860001,78.470001,15.180,1.471692,84.860001,9076,770189.37
1,6,1447.160034,85.570000,78.370003,15.285,1.474491,85.570000,5901,504948.57
2,13,1411.630005,85.129997,77.309998,15.167,1.475492,85.129997,6923,589354.97
3,37,1416.180054,84.769997,75.500000,15.053,1.468299,84.769997,8517,721986.06
4,45,1390.189941,86.779999,76.059998,15.590,1.557099,86.779999,4842,420188.76

In [42]:
X = df.drop("GLD", axis=1)
y = df["GLD"]

In [43]:
scaler = StandardScaler()

X = scaler.fit_transform(X)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=42
)

Q1

In [46]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score

In [47]:
k_values = [3, 5, 7, 11, 13, 15]

best_score = -1
best_k = None

In [48]:
for k in k_values:

    knn = KNeighborsRegressor(n_neighbors=k)

    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)

    score = r2_score(y_test, y_pred)

    print(f"K = {k}, R2 Score = {score:.4f}")

    if score > best_score:
        best_score = score
        best_k = k

K = 3, R2 Score = 0.9879
K = 5, R2 Score = 0.9858
K = 7, R2 Score = 0.9851
K = 11, R2 Score = 0.9821
K = 13, R2 Score = 0.9815
K = 15, R2 Score = 0.9801

In [49]:
print("Best K Value :", best_k)
print("Best R2 Score :", round(best_score, 4))

Best K Value : 3
Best R2 Score : 0.9879

Q2

In [51]:
from sklearn.svm import SVR
from sklearn.metrics import r2_score

In [52]:
C_values = [1, 10, 20]
kernels = ["linear", "rbf"]

best_score = -1
best_C = None
best_kernel = None

In [53]:
for C in C_values:
    for kernel in kernels:

        svr = SVR(C=C, kernel=kernel)

        svr.fit(X_train, y_train)

        y_pred = svr.predict(X_test)

        score = r2_score(y_test, y_pred)

        print(f"C = {C}, Kernel = {kernel}, R2 Score = {score:.4f}")

        if score > best_score:
            best_score = score
            best_C = C
            best_kernel = kernel

C = 1, Kernel = linear, R2 Score = 1.0000
C = 1, Kernel = rbf, R2 Score = 0.9740
C = 10, Kernel = linear, R2 Score = 1.0000
C = 10, Kernel = rbf, R2 Score = 0.9991
C = 20, Kernel = linear, R2 Score = 1.0000
C = 20, Kernel = rbf, R2 Score = 0.9996

In [54]:
print("Best C Value :", best_C)
print("Best Kernel :", best_kernel)
print("Best R2 Score :", round(best_score, 4))

Best C Value : 20
Best Kernel : linear
Best R2 Score : 1.0

Q3

In [56]:
from sklearn.model_selection import GridSearchCV

In [57]:
param_grid = {
    "C": [1, 10, 20],
    "kernel": ["linear", "rbf"]
}

In [58]:
grid = GridSearchCV(
    estimator=SVR(),
    param_grid=param_grid,
    cv=5,
    scoring="r2"
)

In [59]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [1, 10, 20], 'kernel': ['linear', 'rbf']},
             scoring='r2')

In [60]:
print("Best Parameters :", grid.best_params_)
print("Best Cross Validation Score :", round(grid.best_score_, 4))

Best Parameters : {'C': 10, 'kernel': 'linear'}
Best Cross Validation Score : 1.0

In [61]:
best_svr = grid.best_estimator_

y_pred = best_svr.predict(X_test)

r2 = r2_score(y_test, y_pred)

print("Test R2 Score :", round(r2, 4))

Test R2 Score : 1.0

Q4

In [63]:
from sklearn.model_selection import RandomizedSearchCV

In [64]:
param_dist = {
    "C": [1, 10, 20],
    "kernel": ["linear", "rbf"]
}

In [65]:
random = RandomizedSearchCV(
    estimator=SVR(),
    param_distributions=param_dist,
    n_iter=5,
    cv=5,
    scoring="r2",
    random_state=42
)

In [66]:
random.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVR(), n_iter=5,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['linear', 'rbf']},
                   random_state=42, scoring='r2')

In [67]:
print("Best Parameters :", random.best_params_)
print("Best Cross Validation Score :", round(random.best_score_, 4))

Best Parameters : {'kernel': 'linear', 'C': 10}
Best Cross Validation Score : 1.0

In [68]:
best_random = random.best_estimator_

y_pred = best_random.predict(X_test)

r2 = r2_score(y_test, y_pred)

print("Test R2 Score :", round(r2, 4))

Test R2 Score : 1.0

Q5

In [69]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [70]:
rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [71]:
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [72]:
y_pred = rf.predict(X_test)

In [73]:
r2 = r2_score(y_test, y_pred)

print("R2 Score :", round(r2, 4))

R2 Score : 1.0

Q6

In [74]:
from sklearn.ensemble import AdaBoostRegressor, GradientBoostingRegressor
from sklearn.metrics import r2_score

In [75]:
ada = AdaBoostRegressor(
    n_estimators=100,
    random_state=42
)

gb = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

In [76]:
ada.fit(X_train, y_train)
gb.fit(X_train, y_train)

GradientBoostingRegressor(random_state=42)

In [77]:
ada_pred = ada.predict(X_test)

gb_pred = gb.predict(X_test)

In [78]:
ada_r2 = r2_score(y_test, ada_pred)

gb_r2 = r2_score(y_test, gb_pred)

print("AdaBoost R2 Score :", round(ada_r2, 4))
print("Gradient Boosting R2 Score :", round(gb_r2, 4))

AdaBoost R2 Score : 0.9958
Gradient Boosting R2 Score : 0.9999

Q7

In [79]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score

In [80]:
xgb = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

In [81]:
xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [82]:
xgb_pred = xgb.predict(X_test)

In [83]:
xgb_r2 = r2_score(y_test, xgb_pred)

print("XGBoost R2 Score :", round(xgb_r2, 4))

XGBoost R2 Score : 0.9998

Q8

In [84]:
from sklearn.model_selection import GridSearchCV

In [85]:
param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [None, 5, 10],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

In [86]:
grid_rf = GridSearchCV(
    estimator=RandomForestRegressor(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1
)

In [88]:
grid_rf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [None, 5, 10], 'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 100, 200]},
             scoring='r2')

In [89]:
print("Best Parameters :", grid_rf.best_params_)
print("Best Cross Validation Score :", round(grid_rf.best_score_, 4))

Best Parameters : {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}
Best Cross Validation Score : 0.9999

In [90]:
best_rf = grid_rf.best_estimator_

y_pred = best_rf.predict(X_test)

r2 = r2_score(y_test, y_pred)

print("Test R2 Score :", round(r2, 4))

Test R2 Score : 1.0

Q9

In [91]:
knn_pred = knn.predict(X_test)
svr_pred = best_svr.predict(X_test)
rf_pred = best_rf.predict(X_test)
ada_pred = ada.predict(X_test)
gb_pred = gb.predict(X_test)
xgb_pred = xgb.predict(X_test)

In [92]:
knn_r2 = r2_score(y_test, knn_pred)
svr_r2 = r2_score(y_test, svr_pred)
rf_r2 = r2_score(y_test, rf_pred)
ada_r2 = r2_score(y_test, ada_pred)
gb_r2 = r2_score(y_test, gb_pred)
xgb_r2 = r2_score(y_test, xgb_pred)

In [93]:
results = pd.DataFrame({
    "Model": [
        "KNN Regressor",
        "SVR",
        "Random Forest",
        "AdaBoost",
        "Gradient Boosting",
        "XGBoost"
    ],
    "R2 Score": [
        knn_r2,
        svr_r2,
        rf_r2,
        ada_r2,
        gb_r2,
        xgb_r2
    ]
})
results = results.sort_values(
    by="R2 Score",
    ascending=False
)
print(results)

               Model  R2 Score
1                SVR  0.999996
2      Random Forest  0.999963
4  Gradient Boosting  0.999898
5            XGBoost  0.999800
3           AdaBoost  0.995806
0      KNN Regressor  0.980128

In [94]:
best_model_name = results.iloc[0]["Model"]
best_score = results.iloc[0]["R2 Score"]

print("Best Model :", best_model_name)
print("Best R2 Score :", round(best_score, 4))

Best Model : SVR
Best R2 Score : 1.0

Q10

In [95]:
import joblib

joblib.dump(best_rf, "best_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Best model saved successfully.")

Best model saved successfully.

In [96]:
from google.colab import files

files.download("best_model.pkl")
files.download("scaler.pkl")